const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  // Window Controls
  closeWindow: () => ipcRenderer.send('window-close'),
  minimizeWindow: () => ipcRenderer.send('window-minimize'),
  maximizeWindow: () => ipcRenderer.send('window-maximize'),
  beginOperatorControl: (payload = {}) => ipcRenderer.invoke('orion:operator-control-begin', payload),
  endOperatorControl: (payload = {}) => ipcRenderer.invoke('orion:operator-control-end', payload),
  
  // Workspace Actions
  selectWorkspace: () => ipcRenderer.invoke('select-workspace'),
  showConfirmDialog: (message, title) => ipcRenderer.invoke('show-confirm-dialog', { message, title }),
  launchWorkspaceApp: (workspacePath) => ipcRenderer.invoke('launch-workspace-app', workspacePath),
  getWorkspaceEntrypoint: (workspacePath) => ipcRenderer.invoke('get-workspace-entrypoint', workspacePath),
  setWorkspaceEntrypoint: (workspacePath, entrypoint) => ipcRenderer.invoke('set-workspace-entrypoint', { workspacePath, entrypoint }),
  getWorkspaceTestCommand: (workspacePath) => ipcRenderer.invoke('get-workspace-test-command', workspacePath),
  setWorkspaceTestCommand: (workspacePath, testCommand) => ipcRenderer.invoke('set-workspace-test-command', { workspacePath, testCommand }),
  openWorkspaceFolder: (workspacePath) => ipcRenderer.invoke('open-workspace-folder', workspacePath),
  gitPush: (workspacePath, remote, branch, setUpstream) => ipcRenderer.invoke('git-push', { workspacePath, remote, branch, setUpstream }),
  gitDiff: (workspacePath, relativePath) => ipcRenderer.invoke('git-diff', { workspacePath, relativePath }),
  gitRollback: (workspacePath, relativePath) => ipcRenderer.invoke('git-rollback', { workspacePath, relativePath }),
  editConfig: (workspacePath, relativePath, updates) => ipcRenderer.invoke('edit-config', { workspacePath, relativePath, updates }),
  listDirectoryChildren: (dirPath) => ipcRenderer.invoke('list-directory-children', dirPath),
  listFiles: (dirPath) => ipcRenderer.invoke('list-files', dirPath),
  grepSearch: (workspacePath, pattern, options) => ipcRenderer.invoke('grep-search', { workspacePath, pattern, options }),
  readFile: (workspacePath, relativePath, options) => ipcRenderer.invoke('read-file', { workspacePath, relativePath, options }),
  readMultipleRanges: (workspacePath, files, options) => ipcRenderer.invoke('read-multiple-ranges', { workspacePath, files, options }),
  inspectCodeContext: (workspacePath, request) => ipcRenderer.invoke('orion:inspect-code-context', { ...(request || {}), workspacePath }),
  assignContextPackets: (workspacePath, packetIds, handoff) => ipcRenderer.invoke('orion:assign-context-packets', { workspacePath, packetIds, ...(handoff || {}) }),
  hydrateContextPackets: (workspacePath, packetIds, options) => ipcRenderer.invoke('orion:hydrate-context-packets', { workspacePath, packetIds, ...(options || {}) }),
  deletePath: (workspacePath, relativePath) => ipcRenderer.invoke('delete-path', { workspacePath, relativePath }),
  movePath: (workspacePath, fromPath, toPath) => ipcRenderer.invoke('move-path', { workspacePath, fromPath, toPath }),
  renamePath: (workspacePath, relativePath, newName) => ipcRenderer.invoke('rename-path', { workspacePath, relativePath, newName }),
  copyPath: (workspacePath, fromPath, toPath) => ipcRenderer.invoke('copy-path', { workspacePath, fromPath, toPath }),
  downloadFile: (workspacePath, url, destination) => ipcRenderer.invoke('download-file', { workspacePath, url, destination }),
  inspectArchive: (workspacePath, relativePath) => ipcRenderer.invoke('inspect-archive', { workspacePath, relativePath }),
  extractArchive: (workspacePath, relativePath, destination) => ipcRenderer.invoke('extract-archive', { workspacePath, relativePath, destination }),
  inspectBinaryAsset: (workspacePath, relativePath) => ipcRenderer.invoke('inspect-binary-asset', { workspacePath, relativePath }),
  listAssetMetadata: (workspacePath, relativePath) => ipcRenderer.invoke('list-asset-metadata', { workspacePath, relativePath }),
  writeFile: (workspacePath, relativePath, content) => ipcRenderer.invoke('write-file', { workspacePath, relativePath, content }),
  patchFile: (workspacePath, relativePath, operation) => ipcRenderer.invoke('patch-file', { workspacePath, relativePath, operation }),
  getHomeDir: () => ipcRenderer.invoke('get-home-dir'),
  getUserDataPath: () => ipcRenderer.invoke('get-user-data-path'),
  writeRunArtifact: (payload) => ipcRenderer.invoke('write-run-artifact', payload),
  listRunArtifacts: (conversationId) => ipcRenderer.invoke('list-run-artifacts', conversationId),
  writeConversationArtifact: (conversationId, relativePath, content) => ipcRenderer.invoke('write-conversation-artifact', { conversationId, relativePath, content }),
  readConversationArtifact: (conversationId, relativePath, options) => ipcRenderer.invoke('read-conversation-artifact', { conversationId, relativePath, options }),
  deleteConversationArtifacts: (conversationId) => ipcRenderer.invoke('delete-conversation-artifacts', conversationId),
  googleSearch: (query, apiKey, searchEngineId, numResults) => ipcRenderer.invoke('google-search', { query, apiKey, searchEngineId, numResults }),
  fetchWebPage: (url) => ipcRenderer.invoke('fetch-web-page', { url }),
  getPhoneCompanionPairing: () => ipcRenderer.invoke('get-phone-companion-pairing'),
  enablePhoneCompanionLan: () => ipcRenderer.invoke('enable-phone-companion-lan'),
  getPhoneCompanionDevices: () => ipcRenderer.invoke('get-phone-companion-devices'),
  revokePhoneCompanionDevice: (deviceId) => ipcRenderer.invoke('revoke-phone-companion-device', deviceId),
  revokeAllPhoneCompanionDevices: () => ipcRenderer.invoke('revoke-all-phone-companion-devices'),
  notifyPhone: (title, body, context = {}) => ipcRenderer.invoke('notify-phone', {
    title,
    body,
    conversationId: String(context && context.conversationId || '')
  }),
  syncPhoneCompanion: () => ipcRenderer.send('orion:phone-companion-sync'),
  browserOpenUrl: (url) => ipcRenderer.invoke('browser-open-url', { url }),
  browserSearchWeb: (query) => ipcRenderer.invoke('browser-search-web', { query }),
  browserClickElement: (selector, text) => ipcRenderer.invoke('browser-click-element', { selector, text }),
  browserFillInput: (selector, value) => ipcRenderer.invoke('browser-fill-input', { selector, value }),
  browserNavigateBack: () => ipcRenderer.invoke('browser-navigate-back'),
  browserClose: (expectedUrlContains = '') => ipcRenderer.invoke('browser-close', { expectedUrlContains }),
  browserDownloadFromPage: (workspacePath, selector, url, destination) => ipcRenderer.invoke('browser-download-from-page', { workspacePath, selector, url, destination }),
  browserWaitForPage: (timeoutMs) => ipcRenderer.invoke('browser-wait-for-page', { timeoutMs }),
  takeScreenshot: (workspacePath, destination, conversationId) => ipcRenderer.invoke('take-screenshot', { workspacePath, destination, conversationId }),
  showAgentBrowser: () => ipcRenderer.invoke('show-agent-browser'),
  previewApp: (workspacePath, options = {}) => ipcRenderer.invoke('preview-workspace-app', { workspacePath, command: options.command, warmupMs: options.warmupMs, destination: options.destination, processId: options.processId, timeoutMs: options.timeoutMs, conversationId: options.conversationId }),
  captureScreen: (workspacePath, options = {}) => ipcRenderer.invoke('capture-screen', { workspacePath, destination: options.destination, delayMs: options.delayMs, conversationId: options.conversationId, displayId: options.displayId }),
  recordInspectedScreenshot: (workspacePath, relativePath, conversationId = '') => ipcRenderer.invoke('record-inspected-screenshot', { workspacePath, path: relativePath, conversationId }),
  computerAction: (workspacePath, action, conversationId, destination = '', displayId = '') => ipcRenderer.invoke('computer-action', { workspacePath, action, conversationId, destination, displayId }),
  openApplication: (payload = {}) => ipcRenderer.invoke('open-application', payload),
  clickAccessibleUi: (payload = {}) => ipcRenderer.invoke('click-accessible-ui', payload),
  openChromeFavorite: (payload = {}) => ipcRenderer.invoke('open-chrome-favorite', payload),
  inspectScreenshot: (workspacePath, relativePath) => ipcRenderer.invoke('inspect-screenshot', { workspacePath, relativePath }),
  readWorkspaceFileBase64: (workspacePath, relativePath, conversationId = '') => ipcRenderer.invoke('read-workspace-file-base64', { workspacePath, relativePath, conversationId }),
  compareScreenshotToGoal: (workspacePath, relativePath, goal, observations) => ipcRenderer.invoke('compare-screenshot-to-goal', { workspacePath, relativePath, goal, observations }),
  indexWorkspace: (workspacePath) => ipcRenderer.invoke('index-workspace', workspacePath),
  searchEmbeddings: (query, limit) => ipcRenderer.invoke('search-embeddings', { query, limit }),
  semanticSearch: (query, workspacePath, config, topK) => ipcRenderer.invoke('orion:semantic-search', { query, workspacePath, config, topK }),
  getSymbolIndex: (workspacePath) => ipcRenderer.invoke('orion:get-symbol-index', workspacePath),
  getFileSymbols: (workspacePath, relativePath) => ipcRenderer.invoke('orion:get-file-symbols', { workspacePath, relativePath }),
  runLinter: (workspacePath, linterType, targetPath) => ipcRenderer.invoke('orion:run-linter', { workspacePath, linterType, targetPath }),
  findReferences: (workspacePath, symbolName, targetPath) => ipcRenderer.invoke('orion:find-references', { workspacePath, symbolName, targetPath }),
  readProjectMemory: (workspacePath) => ipcRenderer.invoke('orion:read-project-memory', workspacePath),
  recordFileRead: (workspacePath, relativePath) => ipcRenderer.invoke('orion:record-file-read', { workspacePath, relativePath }),
  saveFileDigest: (workspacePath, relativePath, digest) => ipcRenderer.invoke('orion:save-file-digest', { workspacePath, relativePath, digest }),
  getKnowledgeBrief: (workspacePath, maxDigests) => ipcRenderer.invoke('orion:get-knowledge-brief', { workspacePath, maxDigests }),
  writeProjectMemory: (workspacePath, memory) => ipcRenderer.invoke('orion:write-project-memory', { workspacePath, memory }),
  appendProjectMemory: (workspacePath, fact) => ipcRenderer.invoke('orion:append-project-memory', { workspacePath, fact }),
  
  // Update checker
  checkLocalUpdate: () => ipcRenderer.invoke('check-local-update'),
  applyLocalUpdate: () => ipcRenderer.invoke('apply-local-update'),
  checkGitUpdate: () => ipcRenderer.invoke('check-local-update'),
  applyGitUpdate: () => ipcRenderer.invoke('apply-local-update'),
  restartApp: () => ipcRenderer.invoke('restart-app'),

  // Config Controls
  readConfig: () => ipcRenderer.invoke('read-config'),
  getAppRuntimeInfo: () => ipcRenderer.invoke('get-app-runtime-info'),
  writeConfig: (config) => ipcRenderer.invoke('write-config', config),
  readConversationsIndex: () => ipcRenderer.invoke('read-conversations-index'),
  readConversation: (id) => ipcRenderer.invoke('read-conversation', id),
  searchConversationEvidence: (payload) => ipcRenderer.invoke('orion:search-conversation-evidence', payload),
  createOrchestrationTask: (task) => ipcRenderer.invoke('orion:create-task', task),
  getOrchestrationTask: (taskId) => ipcRenderer.invoke('orion:get-task', taskId),
  listOrchestrationTasks: (filters) => ipcRenderer.invoke('orion:list-tasks', filters || {}),
  updateOrchestrationTask: (taskId, patch) => ipcRenderer.invoke('orion:update-task', { taskId, patch }),
  transitionOrchestrationTask: (taskId, status, details) => ipcRenderer.invoke('orion:transition-task', { taskId, status, details }),
  cancelOrchestrationTask: (taskId, requester, reason) => ipcRenderer.invoke('orion:cancel-task', { taskId, requester, reason }),
  reconcileOrchestrationTasks: (payload) => ipcRenderer.invoke('orion:reconcile-tasks', payload || {}),
  migrateOrchestrationTasks: () => ipcRenderer.invoke('orion:migrate-tasks'),
  acquireResourceLease: (payload) => ipcRenderer.invoke('orion:acquire-lease', payload || {}),
  releaseResourceLease: (payload) => ipcRenderer.invoke('orion:release-lease', payload || {}),
  releaseResourceLeasesForConversation: (conversationId) => ipcRenderer.invoke('orion:release-leases-for-conversation', conversationId),
  heartbeatResourceLease: (payload) => ipcRenderer.invoke('orion:heartbeat-lease', payload || {}),
  listResourceLeases: (filters) => ipcRenderer.invoke('orion:list-leases', filters || {}),
  reconcileResourceLeases: (payload) => ipcRenderer.invoke('orion:reconcile-leases', payload || {}),
  resolveResourceLeaseLiveness: (payload) => ipcRenderer.invoke('orion:resolve-lease-liveness', payload || {}),
  createSchedule: (input) => ipcRenderer.invoke('orion:create-schedule', input || {}),
  listSchedules: (filters) => ipcRenderer.invoke('orion:list-schedules', filters || {}),
  cancelSchedule: (scheduleId) => ipcRenderer.invoke('orion:cancel-schedule', { scheduleId }),
  cancelConversationSchedules: (conversationId) => ipcRenderer.invoke('orion:cancel-conversation-schedules', { conversationId }),
  cancelTaskSchedules: (sourceTaskId) => ipcRenderer.invoke('orion:cancel-task-schedules', { sourceTaskId }),
  writeConversation: (conv) => ipcRenderer.invoke('write-conversation', conv),
  writeConversationsIndex: (index) => ipcRenderer.invoke('write-conversations-index', index),
  deleteConversation: (id) => ipcRenderer.invoke('delete-conversation', id),
  
  // Shell Runner
  runCommand: (command, cwd, processId, timeoutMs) => ipcRenderer.invoke('run-command', { command, cwd, processId, timeoutMs }),
  runDatabaseQuery: (payload) => ipcRenderer.invoke('orion:db-query', payload),
  startCommand: (command, cwd, processId, timeoutMs) => ipcRenderer.invoke('start-command', { command, cwd, processId, timeoutMs }),
  getCommandStatus: (processId) => ipcRenderer.invoke('get-command-status', processId),
  readCommandOutput: (processId, maxChars) => ipcRenderer.invoke('read-command-output', { processId, maxChars }),
  killCommand: (processId) => ipcRenderer.invoke('kill-command', processId),
  checkProcessAlive: (pid) => ipcRenderer.invoke('check-process-alive', pid),
  killCommandsForConversation: (conversationId) => ipcRenderer.invoke('kill-commands-for-conversation', conversationId),
  onCommandOutput: (processId, callback) => {
    const listener = (event, data) => callback(data);
    ipcRenderer.on(`cmd-output-${processId}`, listener);
    // Return clean-up function
    return () => {
      ipcRenderer.removeListener(`cmd-output-${processId}`, listener);
    };
  },

  // Skill Registry
  discoverSkills: (group) => ipcRenderer.invoke('orion:discover-skills', { group }),
  runSkill: (name, inputs) => ipcRenderer.invoke('orion:run-skill', { name, inputs }),
  createSkill: (payload) => ipcRenderer.invoke('orion:create-skill', payload),
  listSkillGroups: () => ipcRenderer.invoke('orion:list-skill-groups'),

  // Global Memory
  readGlobalMemory: () => ipcRenderer.invoke('orion:read-global-memory'),
  writeGlobalMemory: (updates) => ipcRenderer.invoke('orion:write-global-memory', updates),
  appendGlobalFact: (text, category, config, pinned) => ipcRenderer.invoke('orion:append-global-fact', { text, category, config, pinned }),
  appendGlobalPreference: (text, config, source, mode, pinned) => ipcRenderer.invoke('orion:append-global-preference', { text, config, source, mode, pinned }),
  updateUserProfile: (updates) => ipcRenderer.invoke('orion:update-user-profile', { updates }),
  rankMemoryFacts: (query, config, limit, mode) => ipcRenderer.invoke('orion:rank-memory-facts', { query, config, limit, mode }),

  // Project Memory (extended)
  appendProjectFact: (workspacePath, text, category, config, pinned) => ipcRenderer.invoke('orion:append-project-fact', { workspacePath, text, category, config, pinned }),
  appendProjectDecision: (workspacePath, text, context) => ipcRenderer.invoke('orion:append-project-decision', { workspacePath, text, context }),
  appendProjectPreference: (workspacePath, text, config, mode, pinned) => ipcRenderer.invoke('orion:append-project-preference', { workspacePath, text, config, mode, pinned }),

  // Skill Memory
  readSkillMemory: () => ipcRenderer.invoke('orion:read-skill-memory'),
  appendSkillPattern: (pattern) => ipcRenderer.invoke('orion:append-skill-pattern', { pattern }),

  // Session Memory
  saveSession: (workspacePath, sessionData) => ipcRenderer.invoke('orion:save-session', { workspacePath, sessionData }),
  listSessions: (workspacePath, limit) => ipcRenderer.invoke('orion:list-sessions', { workspacePath, limit }),
  readSession: (workspacePath, sessionId) => ipcRenderer.invoke('orion:read-session', { workspacePath, sessionId }),

  // Crash safety — the renderer's global error traps forward here so browser-side
  // faults reach the same on-disk crash log as main-process ones.
  reportRendererFault: (kind, detail) => ipcRenderer.send('orion:report-renderer-fault', { kind, detail }),
  onMainFault: (callback) => ipcRenderer.on('orion:main-fault', (event, payload) => callback(payload))
});
